Algoritmo "divisão"
// 
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/01/2023
Var
// Seção de Declarações das variáveis 
n1,n2:inteiro
divi:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("escreva um valor: ")
leia(n1)
escreva("escreva outro valor: ")
leia(n2)
divi<-(n1\n2)
escreva("A divisão de",n1," e",n2," è",divi)

Fimalgoritmo