Algoritmo "multiplicação"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/01/2023
Var
// Seção de Declarações das variáveis 
n1,n2:inteiro
mult:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("escreva um numero: ")
leia(n1)
escreva("escreva outro numero: ")
leia(n2)
mult<-(n1*n2)
escreva("A multiplicação de",n1," e",n2," è de",mult)

Fimalgoritmo