Algoritmo "OPE_LOGICOS"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/01/2023
Var
// Seção de Declarações das variáveis 
a, b, c: REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a<-2
b<-3
c<-5

escreval((a=b)  E (a=c))
escreval((a<b) E (a<>c) E (b<>c))
escreval((a<>b) OU (c>a+c))
escreval((c=a+b) OU (c=a-b))

Fimalgoritmo