Algoritmo "peso,altura"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/01/2023
Var
// Seção de Declarações das variáveis 
peso,altura:real
final:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("qual seu peso: ")
leia(peso)
escreva("qual sua altura: ")
leia(altura)
final<-peso\altura^2
escreva("á sua média corporal é de:",final)

Fimalgoritmo