Algoritmo "subtrasão"
// 
//
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/01/2023
Var
// Seção de Declarações das variáveis 
n1,n2:inteiro
sub:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("digite um numero:")
leia(n1)
escreva("digite um segundo numero")
leia(n2)
sub<-(n1-n2)
escreva("A subtração entre ",n1," e",n2," é",sub)
Fimalgoritmo